@isTest(SeeAllData=true)
public class tmp_test {
  /// this is a tmp class helping me while removing the following objects

  /*	
    static testmethod void PrintInvoicesControllerTest(){	
    	PrintInvoicesController piv =  new PrintInvoicesController();
    }
	*/
  static testMethod void AddProductFromOpportuntiyEXTTest() {
    AddProductFromOpportuntiyEXT ap = new AddProductFromOpportuntiyEXT();
  }

  static testMethod void eventRegistrationControllerTest() {
    eventRegistrationController ec = new eventRegistrationController();
  }
}
